version: 2
registries:
  npm-registry-registry-npmjs-org:
    type: npm-registry
    url: https://registry.npmjs.org
    token: "${{secrets.NPM_REGISTRY_REGISTRY_NPMJS_ORG_TOKEN}}"

updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "23:30"
  open-pull-requests-limit: 10
  reviewers:
  - hybridx
  assignees:
  - hybridx
  ignore:
  - dependency-name: webpack
    versions:
    - 5.19.0
    - 5.26.3
  - dependency-name: mini-css-extract-plugin
    versions:
    - 1.3.5
  registries:
  - npm-registry-registry-npmjs-org
